### ISSUE TITLE
Adding certificate to apache /etc/ssl/certs/

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/odn-cas#2]
created from OpenDataNode/odn-box#23

Motivation:
odn-cas is responsible for creation certificate for host. It puts a generated certificate to `/usr/local/share/ca-certificates/` and `/usr/share/odn-cas/conf/.keystore` at [odn-cas:generate_keystore()](https://github.com/OpenDataNode/odn-cas/blob/master/src/deb/control/postinst#L61). odn-cas should place the cerificate to `/etc/ssl/certs/` as well.  ( /etc/ssl/certs/ is important for apache2 because it reads certs from here). This function [apache_ssl() at odn-cas](https://github.com/OpenDataNode/odn-box/blob/master/debian/odn-simple.postinst#L150) is hot fix - It takes cert from `/usr/share/odn-cas/conf/.keystore` and put to `/etc/ssl/certs/`. 

odn-cas shall propagate generated certificate to the all important places.

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/odn-box/commit/3e8140c00e64e47161dff45e89b91a83b95f2f88
and by https://github.com/OpenDataNode/odn-cas/commit/b830b13e208865ceb4d4c6aa2f28ab6fb9b0e345

**Comment by Jan-Marcek** [comment]
The solution.
odn-cas creates certificate and private key. It places certificate to  `/etc/odn-cas/ssl/certs`. It places private key to  `/etc/odn-cas/ssl/private`
These certificates are loaded to odn-cas keystore.

it creates link  `/usr/local/share/ca-certificates/odn-cert.pem` then update-ca-certificates propagates this cert to  `/etc/ssl/certs/`

odn-simple brings odn-simple-ssl-apache.conf where parameters are set as 

```
SSLCertificateFile    /etc/odn-cas/ssl/certs/odn-cert.pem
SSLCertificateKeyFile /etc/odn-cas/ssl/private/odn-key.pem
```
